### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by MinhDuc21** [TwinKleS-C/TwinKleS.ToolKit.WindowsExplorerExtension#1]
Hello, I'm trying to translate this tool for easier using. But after I translated it and built it back in Visual Studio, then installed it, I can't find TwinKleS option in the context menu, even after I restarted my PC. Do you know what wrong? Also thanks for your great tool.

**Comment by TwinKleS-C** [comment]
1. 由我构建的拓展程序在你的设备上是否有效？
2. 在你重新构建项目并安装后，能否在任务管理器中看到 TwinKleS 进程？
如果方便，请发生以下文件至我的邮箱 twinkles.china@gmail.com ：
1. 你修改后的vs项目
2. 你所构建的msixbundle文件
3. 你的cer证书文件

1. Does the extension built by me work on your device?
2. After you rebuild the project and install, can you see the TwinKleS process in the task manager?
If it is convenient, please send the following files to my mailbox twinkles.china@gmail.com :
1. Your modified vs project
2. The msixbundle file you built
3. Your cer certificate file

**Comment by MinhDuc21** [comment]
1. Yes, your extension worked perfectly on my device
2. I don't see TwinKleS process in the Task Manager after I rebuilt the project and install, even after I restarted my PC

I just sent these file into you email.

**Comment by TwinKleS-C** [comment]
I did not receive your email

**Comment by MinhDuc21** [comment]
Hmmm, that's weird. But thanks anyway, my friend just rebuilt it and fix it for me. I must replace the implement.dll in C:\Program Files\WindowsApps\TwinKleS.ToolKit.WindowsExplorerExtension_[1.0.0.0]_x64__y8ab8ryfz16bm\Assets\Library with his implement.dll. And it finally worked. Here is the file if you still need. His implement.dll is in implement.zip
[TWS_Extension_ETrans.zip](https://github.com/TwinKleS-C/TwinKleS.ToolKit.WindowsExplorerExtension/files/8650115/TWS_Extension_ETrans.zip)

**Comment by TwinKleS-C** [comment]
这是正常情况，虽然我忘了说明这点。
项目中的 <project>/package/Assets/Library/implement.dll 实际上是一个指向 <project>/.out/x64-Release/implement/implement.dll 的符号链接，在每次构建 implement 子项目后，都应运行 <project>/package/Assets/Library/link.bat 文件以创建这一符号链接，以使vs将真正的 implement.dll 打包进msix。
在你之前的构建中，由于没有执行link.bat，Library/implement.dll 的实际内容为一个描述该符号链接指向路径的字符串，因此打包安装后无法正确地加载 implement.dll 。

// eng

This is normal, although I forgot to state this.
The <project>/package/Assets/Library/implement.dll in the project is actually a symlink to <project>/.out/x64-Release/implement/implement.dll, after every build of the implement subproject, Both should run the <project>/package/Assets/Library/link.bat file to create this symlink for VS to package the real implement.dll into msix.
In your previous build, since link.bat was not executed, the actual content of Library/implement.dll was a string describing the path to which the symbolic link pointed, so implement.dll could not be loaded correctly after packaged installation.
